language: python
python:
  - "2.7"
env:
    - TOX_ENV=flake8
    - TOX_ENV=py27
    - TOX_ENV=py26
# TODO: add coveralls support
install:
    - pip install tox
    # - pip install coveralls
script:
    - tox -e $TOX_ENV
# after_success:
#     coveralls